version: "3.7"
services:
  influxdb:
    image: influxdb:1.8.4
    ports:
      - "8086:8086"
    networks:
      - ticknet
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - ./configs/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    restart: unless-stopped

  kapacitor:
    image: kapacitor:1.5.8
    ports:
      - "9092:9092"
    networks:
      - ticknet
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_CONFIG_PATH=/etc/kapacitor/kapacitor.conf
    volumes:
      - ./configs/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./data/kapacitor:/var/lib/kapacitor
      - ./data/logs:/tmp
    depends_on:
      - influxdb
    restart: unless-stopped

  chronograf:
    image: chronograf
    ports:
      - "5000:8888"
    networks:
      - ticknet
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_URL=http://kapacitor:9092
      - REPORTING_DISABLED=1
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
      - kapacitor
    restart: unless-stopped

  telegraf:
    image: telegraf
    networks:
      - ticknet
    environment:
      - TELEGRAF_HOST=${TELEGRAF_HOST}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    restart: unless-stopped

networks:
  ticknet: